# Use the official Node.js 14 image with Alpine Linux as the base image
FROM node:14-alpine

# Set the working directory inside the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Run npm install to install dependencies based on the package.json
RUN npm install

# Copy the entire local directory to the working directory in the container
COPY . .

# Expose port 3000 to allow external connections to the application
EXPOSE 3000
